package main

import (
	"bufio"
	"flag"
	"fmt"
	"os"
	"os/exec"
	"regexp"
	"strings"

	"github.com/est57/kl-go-cli/internal/generator"
)

const version = "0.3.0"

const usage = `kl-go-cli - scaffold Go microservice dengan clean architecture

Usage:
  kl-go-cli new [service-name] [flags]
  kl-go-cli -h | --help
  kl-go-cli -v | --version

Kalau service-name gak diisi, kl-go-cli akan tanya interaktif.

Flags:
  -module string   go module path (default: github.com/kodelokal/<service-name>)
  -port string     port default service (default: "8080")
  -transport string transport scaffold: http, grpc, atau both (default: "http")
  -grpc-port string port default gRPC service (default: "9090")
  -db string       database scaffold: postgres atau none (default: "postgres")
  -out string      output directory (default: nama service)
  -tidy            otomatis jalanin "go mod tidy" setelah generate
  -git             otomatis "git init" + commit pertama setelah generate

Contoh:
  kl-go-cli new
  kl-go-cli new user-service
  kl-go-cli new order-service -module=github.com/tribina/order-service -port=8081 -tidy -git
  kl-go-cli new simple-service -db=none
  kl-go-cli new inventory-service -transport=both -grpc-port=9091
`

func main() {
	if len(os.Args) < 2 {
		fmt.Print(usage)
		os.Exit(1)
	}

	switch os.Args[1] {
	case "-h", "--help", "help":
		fmt.Print(usage)
		return
	case "-v", "--version", "version":
		fmt.Println("kl-go-cli v" + version)
		return
	case "new":
		runNew(os.Args[2:])
	default:
		fmt.Print(usage)
		os.Exit(1)
	}
}

func runNew(args []string) {
	fs := flag.NewFlagSet("new", flag.ExitOnError)
	module := fs.String("module", "", "go module path")
	port := fs.String("port", "8080", "default service port")
	transport := fs.String("transport", "http", "transport scaffold: http, grpc, atau both")
	grpcPort := fs.String("grpc-port", "9090", "default gRPC service port")
	db := fs.String("db", "postgres", "database scaffold: postgres atau none")
	out := fs.String("out", "", "output directory")
	tidy := fs.Bool("tidy", false, "run go mod tidy after generate")
	initGit := fs.Bool("git", false, "run git init + first commit after generate")

	var serviceName string
	if len(args) > 0 && !strings.HasPrefix(args[0], "-") {
		serviceName = args[0]
		args = args[1:]
	}
	if err := fs.Parse(args); err != nil {
		os.Exit(1)
	}

	// lacak flag apa aja yang eksplisit diisi user, biar gak nimpa dengan prompt
	explicit := map[string]bool{}
	fs.Visit(func(f *flag.Flag) { explicit[f.Name] = true })

	reader := bufio.NewReader(os.Stdin)
	interactive := isInteractive()

	if serviceName == "" {
		serviceName = prompt(reader, "Nama service (contoh: user-service): ", "")
	}
	for !validServiceName(serviceName) {
		fmt.Println("nama cuma boleh huruf kecil, angka, dan dash. contoh: user-service")
		serviceName = prompt(reader, "Nama service: ", "")
	}

	if *module == "" && !explicit["module"] {
		defaultModule := "github.com/kodelokal/" + serviceName
		if interactive {
			*module = prompt(reader, fmt.Sprintf("Go module path [%s]: ", defaultModule), defaultModule)
		} else {
			*module = defaultModule
		}
	}

	if !explicit["port"] && interactive {
		*port = prompt(reader, "Port default [8080]: ", "8080")
	}

	if !explicit["transport"] && interactive {
		*transport = prompt(reader, "Transport [http|grpc|both]: ", "http")
	}
	if !validTransport(*transport) {
		fmt.Fprintln(os.Stderr, "error: -transport cuma boleh http, grpc, atau both")
		os.Exit(1)
	}

	if (*transport == "grpc" || *transport == "both") && !explicit["grpc-port"] && interactive {
		*grpcPort = prompt(reader, "Port gRPC [9090]: ", "9090")
	}

	if !explicit["db"] && interactive {
		*db = prompt(reader, "Database [postgres|none]: ", "postgres")
	}
	if !validDatabase(*db) {
		fmt.Fprintln(os.Stderr, "error: -db cuma boleh postgres atau none")
		os.Exit(1)
	}

	if *out == "" {
		*out = serviceName
	}

	pkgName := toPackageName(serviceName)

	data := generator.Data{
		ServiceName: serviceName,
		PackageName: pkgName,
		Module:      *module,
		Port:        *port,
		Database:    *db,
		Transport:   *transport,
		GRPCPort:    *grpcPort,
	}

	if err := generator.GenerateService(*out, data); err != nil {
		fmt.Fprintln(os.Stderr, "error:", err)
		os.Exit(1)
	}

	fmt.Printf("\nService %q berhasil dibuat di ./%s\n", serviceName, *out)

	if *tidy {
		fmt.Println("\nmenjalankan go mod tidy...")
		if err := runCmd(*out, "go", "mod", "tidy"); err != nil {
			fmt.Fprintln(os.Stderr, "go mod tidy gagal:", err)
			fmt.Println("jalanin manual: cd", *out, "&& go mod tidy")
			*tidy = false
		} else {
			fmt.Println("selesai.")
		}
	}

	if *initGit {
		fmt.Println("\nsetup git repo...")
		gitignore := "bin/\n.env\n*.log\ntmp/\n"
		_ = os.WriteFile(*out+"/.gitignore", []byte(gitignore), 0o644)
		_ = runCmd(*out, "git", "init")
		_ = runCmd(*out, "git", "add", ".")
		_ = runCmd(*out, "git", "commit", "-m", "init: "+serviceName+" generated by kl-go-cli")
		fmt.Println("selesai.")
	}

	fmt.Printf("\nNext steps:\n  cd %s\n", *out)
	if !*tidy {
		fmt.Println("  go mod tidy")
	}
	fmt.Println("  make run")
	if *transport == "http" || *transport == "both" {
		fmt.Printf("\nHealth check: curl http://localhost:%s/health\n", *port)
	}
	if *transport == "grpc" || *transport == "both" {
		fmt.Printf("gRPC health service: localhost:%s\n", *grpcPort)
	}
}

func prompt(r *bufio.Reader, label, fallback string) string {
	fmt.Print(label)
	line, _ := r.ReadString('\n')
	line = strings.TrimSpace(line)
	if line == "" {
		return fallback
	}
	return line
}

func isInteractive() bool {
	fi, err := os.Stdin.Stat()
	if err != nil {
		return false
	}
	return (fi.Mode() & os.ModeCharDevice) != 0
}

func runCmd(dir, name string, args ...string) error {
	cmd := exec.Command(name, args...)
	cmd.Dir = dir
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	return cmd.Run()
}

var serviceNameRe = regexp.MustCompile(`^[a-z][a-z0-9-]*$`)

func validServiceName(s string) bool {
	return serviceNameRe.MatchString(s)
}

func toPackageName(s string) string {
	return strings.ReplaceAll(s, "-", "_")
}

func validDatabase(s string) bool {
	return s == "postgres" || s == "none"
}

func validTransport(s string) bool {
	return s == "http" || s == "grpc" || s == "both"
}
