.PHONY: run build test tidy docker-up docker-down

run:
	go run ./cmd/api

build:
	go build -o bin/{{.PackageName}} ./cmd/api

test:
	go test ./... -v -cover

tidy:
	go mod tidy

docker-up:
	docker compose up --build

docker-down:
	docker compose down
