FROM golang:1.22-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /bin/{{.PackageName}} ./cmd/api

FROM alpine:3.19
RUN apk --no-cache add ca-certificates tzdata
WORKDIR /root/
COPY --from=builder /bin/{{.PackageName}} .
{{if .HasHTTP}}EXPOSE {{.Port}}{{end}}
{{if .HasGRPC}}EXPOSE {{.GRPCPort}}{{end}}
CMD ["./{{.PackageName}}"]
